CREATE OR REPLACE PROCEDURE SP_GET_BRN_CODE (P_ADMIN_CODE NUMBER, P_FLAG NUMBER , P_LIST_ID NUMBER )
IS
   V_COUNT    NUMBER;
   V_RETURN   NUMBER;
BEGIN
   SELECT COUNT (*)
     INTO V_COUNT
     FROM MBRN
    WHERE MBRN_PARENT_ADMIN_CODE = P_ADMIN_CODE;
   IF V_COUNT = 0
   THEN
      DBMS_OUTPUT.PUT_LINE (P_ADMIN_CODE);
      INSERT INTO BRANCH_ADMIN (LIST_ID, BRANCH_CODE) VALUES (P_LIST_ID, P_ADMIN_CODE);
   ELSE
      BEGIN
         FOR IDX IN (SELECT *
                       FROM MBRN
                      WHERE MBRN_PARENT_ADMIN_CODE = P_ADMIN_CODE)
         LOOP
            V_RETURN := FN_GET_BRN_CODE (IDX.MBRN_CODE, 1, P_LIST_ID);
         END LOOP;
         IF P_FLAG = 1 THEN
            DBMS_OUTPUT.PUT_LINE (P_ADMIN_CODE);
            INSERT INTO BRANCH_ADMIN (LIST_ID, BRANCH_CODE) VALUES (P_LIST_ID, P_ADMIN_CODE);
         END IF ;
      END;
   END IF;
END;
