CREATE OR REPLACE PROCEDURE SP_MARKUP_PROF_AMT (
   V_ENTITY_NUM       IN     NUMBER,
   P_INTERNAL_ACNUM   IN     NUMBER,
   P_DISB_AMOUNT      IN     NUMBER,
   W_MARKUP_PROF         OUT NUMBER)
IS
   W_ERRORMSG                VARCHAR2 (1800);
   V_INT_RATE                NUMBER (10, 7);
   W_CURRENT_DATE            DATE;
   V_EXPITY_DATE             DATE;
   V_MARKUP_PROF             NUMBER;
   V_LNCUR_INT_CALCN_BASIS   VARCHAR2 (1);
   V_FACTOR                  NUMBER;
BEGIN
   W_CURRENT_DATE := PKG_PB_GLOBAL.FN_GET_CURR_BUS_DATE (V_ENTITY_NUM);
   SP_FETCH_LOAN_INT (V_ENTITY_NUM,
                      P_INTERNAL_ACNUM,
                      W_CURRENT_DATE,
                      V_INT_RATE);

   SELECT LMTLINE_LIMIT_EXPIRY_DATE
     INTO V_EXPITY_DATE
     FROM LIMITLINE, ACASLLDTL
    WHERE     ACASLLDTL_ENTITY_NUM = V_ENTITY_NUM
          AND LMTLINE_ENTITY_NUM = V_ENTITY_NUM
          AND ACASLLDTL_CLIENT_NUM = LMTLINE_CLIENT_CODE
          AND ACASLLDTL_LIMIT_LINE_NUM = LMTLINE_NUM
          AND ACASLLDTL_INTERNAL_ACNUM = P_INTERNAL_ACNUM;

   SELECT LNCUR_INT_CALCN_BASIS
     INTO V_LNCUR_INT_CALCN_BASIS
     FROM ACNTS, LNCURPM
    WHERE     ACNTS_ENTITY_NUM = V_ENTITY_NUM
          AND ACNTS_INTERNAL_ACNUM = P_INTERNAL_ACNUM
          AND ACNTS_PROD_CODE = LNCUR_PROD_CODE;

   IF V_LNCUR_INT_CALCN_BASIS = '1'
   THEN
      V_FACTOR := 365;
   ELSIF V_LNCUR_INT_CALCN_BASIS = '2'
   THEN
      V_FACTOR := 360;
   ELSIF V_LNCUR_INT_CALCN_BASIS = '3'
   THEN
      V_FACTOR := 366;
   ELSE
      V_FACTOR := 365;
   END IF;

   W_MARKUP_PROF :=
      ROUND (
           (P_DISB_AMOUNT * V_INT_RATE * (V_EXPITY_DATE - W_CURRENT_DATE))
         / (100 * V_FACTOR),
         2);
EXCEPTION
   WHEN OTHERS
   THEN
      W_MARKUP_PROF := 0;
END SP_MARKUP_PROF_AMT;
/