CREATE OR REPLACE PROCEDURE SP_SECURITY_NUM_CHECK AS
  V_MAX  NUMBER;
  V_MIN  NUMBER;
  DIFF   NUMBER;
  V_SQL1 VARCHAR(300);
  V_SQL2 VARCHAR(300);
  J NUMBER ;
BEGIN

  FOR I IN 1 .. 9 LOOP
    DIFF := 0 ;
    V_SQL1 := 'SELECT MAX(SECRCPT_SECURITY_NUM)  FROM SONALI_MIG_' || I ||
              '.SECRCPT ';


    EXECUTE IMMEDIATE V_SQL1
      INTO V_MAX;
      
      J := I + 1 ;
      
     DBMS_OUTPUT.PUT_LINE(V_SQL1);
     DBMS_OUTPUT.PUT_LINE(V_MAX);
     
     
    V_SQL1 := 'SELECT  MIN(SECRCPT_SECURITY_NUM) FROM SONALI_MIG_' || J ||
              '.SECRCPT';


    EXECUTE IMMEDIATE  V_SQL1
      INTO V_MIN;
                 
    --DIFF := V_MAX - V_MIN - 1;

    DBMS_OUTPUT.PUT_LINE(V_SQL1);
     DBMS_OUTPUT.PUT_LINE(V_MIN);

  END LOOP;
END SP_SECURITY_NUM_CHECK;
/