CREATE OR REPLACE TRIGGER UPDATE_CHECK_MIG_ACNTS_ACCRUAL
  BEFORE UPDATE OF ACNTS_INT_ACCR_UPTO ON MIG_ACNTS
  FOR EACH ROW
DECLARE
  V_SQL VARCHAR2(100);
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_PAID DISABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_ACCRU DISABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_APPLIED DISABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_ACCRU DISABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_PAID DISABLE';
  EXECUTE IMMEDIATE V_SQL;

  :NEW.ACNTS_INT_CALC_UPTO := :NEW.ACNTS_INT_ACCR_UPTO;

  UPDATE MIG_LNACNT
     SET LNACNT_INT_ACCR_UPTO = :NEW.ACNTS_INT_ACCR_UPTO
   WHERE LNACNT_ACNUM = :OLD.ACNTS_ACNUM;

  UPDATE MIG_PBDCONTRACT
     SET MIGDEP_INT_ACCR_UPTO         = :NEW.ACNTS_INT_ACCR_UPTO,
         MIGDEP_INT_CALC_UPTO         = :NEW.ACNTS_INT_ACCR_UPTO,
         MIGDEP_INT_CALC_PAYABLE_UPTO = :NEW.ACNTS_INT_ACCR_UPTO
   WHERE MIGDEP_DEP_AC_NUM = :OLD.ACNTS_ACNUM;

  UPDATE TEMP_LOANIA
     SET LOANIA_VALUE_DATE   = :NEW.ACNTS_INT_ACCR_UPTO,
         LOANIA_ACCRUAL_DATE = :NEW.ACNTS_INT_ACCR_UPTO
   WHERE LOANIA_ACNT_NUM = :OLD.ACNTS_ACNUM;

  UPDATE TEMP_SBCAIA
     SET SBCAIA_UPTO_DATE = :NEW.ACNTS_INT_ACCR_UPTO
   WHERE SBCAIA_INTERNAL_ACNUM = :OLD.ACNTS_ACNUM;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_PAID ENABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_ACCRU ENABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_APPLIED ENABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_ACCRU ENABLE';
  EXECUTE IMMEDIATE V_SQL;

  V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_PAID ENABLE';
  EXECUTE IMMEDIATE V_SQL;

END UPDATE_CHECK_MIG_ACNTS_ACCRUAL;
/
SHOW ERRORS;
/