CREATE OR REPLACE TRIGGER UPDATE_DATEOF_NPA_MIG_LNACNT
   BEFORE UPDATE OF LNACNT_DATE_OF_NPA
   ON MIG_LNACNT
   FOR EACH ROW
DECLARE
   V_SQL   VARCHAR2 (100);
   V_TEMP_AC VARCHAR2(13);
PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
   V_SQL := 'ALTER TRIGGER UPDATE_DATEOF_NPA_MIG_ASSETCLS DISABLE';

   EXECUTE IMMEDIATE V_SQL;


   :NEW.LNACNT_NPA_IDENTIFIED_DATE         := :NEW.LNACNT_DATE_OF_NPA;


   UPDATE MIG_ASSETCLS
      SET ASSETCLSH_NPA_DATE = :NEW.LNACNT_DATE_OF_NPA
   WHERE ASSETCLS_ACNUM=:OLD.LNACNT_ACNUM;


   V_SQL := 'ALTER TRIGGER UPDATE_DATEOF_NPA_MIG_ASSETCLS ENABLE';

   EXECUTE IMMEDIATE V_SQL;
END UPDATE_DATEOF_NPA_MIG_LNACNT;
/
SHOW ERRORS;
/