CREATE OR REPLACE TRIGGER UPDATE_CHECK_MIG_LNACNTS_ASSET
  BEFORE UPDATE OF LNACNT_ASSET_STAT ON MIG_LNACNT
  FOR EACH ROW
DECLARE
  V_SQL VARCHAR2(100);
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

V_SQL:='ALTER TRIGGER UPDATE_CHECK_MIG_ASSETCLS DISABLE';
EXECUTE IMMEDIATE   V_SQL;
  UPDATE MIG_ASSETCLS
     SET ASSETCLSH_ASSET_CODE = :NEW.LNACNT_ASSET_STAT
   WHERE ASSETCLS_ACNUM =:OLD.LNACNT_ACNUM;
   V_SQL:='ALTER TRIGGER UPDATE_CHECK_MIG_ASSETCLS ENABLE';
EXECUTE IMMEDIATE   V_SQL;


END UPDATE_CHECK_MIG_LNACNTS_ASSET;
/
SHOW ERRORS;
/