CREATE OR REPLACE TRIGGER UPDATE_DATEOF_NPA_MIG_ASSETCLS 
   BEFORE UPDATE OF ASSETCLSH_NPA_DATE
   ON MIG_ASSETCLS
   FOR EACH ROW
DECLARE
   V_SQL   VARCHAR2 (100);
PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
   V_SQL := 'ALTER TRIGGER UPDATE_DATEOF_NPA_MIG_LNACNT DISABLE';

   EXECUTE IMMEDIATE V_SQL;


   UPDATE MIG_LNACNT
      SET LNACNT_DATE_OF_NPA = :NEW.ASSETCLSH_NPA_DATE,
      LNACNT_NPA_IDENTIFIED_DATE= :NEW.ASSETCLSH_NPA_DATE
    WHERE LNACNT_ACNUM = :OLD.ASSETCLS_ACNUM;

   V_SQL := 'ALTER TRIGGER UPDATE_DATEOF_NPA_MIG_LNACNT ENABLE';


   EXECUTE IMMEDIATE V_SQL;
END UPDATE_DATEOF_NPA_MIG_ASSETCLS;
/
SHOW ERRORS;
/