CREATE OR REPLACE TRIGGER UPDATE_CHECK_MIG_PBDCONT_ACCRU
   BEFORE UPDATE OF MIGDEP_INT_ACCR_UPTO
   ON MIG_PBDCONTRACT
   FOR EACH ROW
DECLARE
   V_SQL        VARCHAR2 (100);
   V_FD_COUNT   NUMBER;
   PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_ACCRUAL DISABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_PAID DISABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_ACCRU DISABLE';
   EXECUTE IMMEDIATE V_SQL;
   
   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_APPLIED DISABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_PAID DISABLE';
   EXECUTE IMMEDIATE V_SQL;

   :NEW.MIGDEP_INT_CALC_UPTO := :NEW.MIGDEP_INT_ACCR_UPTO;
   :NEW.MIGDEP_INT_CALC_PAYABLE_UPTO := :NEW.MIGDEP_INT_ACCR_UPTO;


   UPDATE MIG_ACNTS
      SET ACNTS_INT_CALC_UPTO = :NEW.MIGDEP_INT_ACCR_UPTO,
          ACNTS_INT_ACCR_UPTO = :NEW.MIGDEP_INT_ACCR_UPTO
    WHERE ACNTS_ACNUM = :OLD.MIGDEP_DEP_AC_NUM;

   UPDATE MIG_DEPIA D
      SET D.DEPIA_DATE_OF_ENTRY = :NEW.MIGDEP_INT_ACCR_UPTO,
          D.DEPIA_ACCR_UPTO_DATE = :NEW.MIGDEP_INT_ACCR_UPTO
    WHERE     D.DEPIA_ACCOUNTNUM = :OLD.MIGDEP_DEP_AC_NUM
          AND D.DEPIA_ENTRY_TYPE = 'IA'
          AND D.DEPIA_DATE_OF_ENTRY =
                 (SELECT MAX (DEPIA_DATE_OF_ENTRY)
                    FROM MIG_DEPIA
                   WHERE     DEPIA_ACCOUNTNUM = :OLD.MIGDEP_DEP_AC_NUM
                         AND DEPIA_ENTRY_TYPE = 'IA');



   SELECT COUNT (*)
     INTO V_FD_COUNT
     FROM MIG_PBDCONTRACT
    WHERE MIGDEP_DEP_AC_NUM = :OLD.MIGDEP_DEP_AC_NUM AND MIGDEP_CONT_NUM = 1;

   IF V_FD_COUNT = 1
   THEN
      :NEW.MIGDEP_INT_PAID_UPTO := :NEW.MIGDEP_INT_ACCR_UPTO;



      UPDATE MIG_ACNTS
         SET ACNTS_INT_DBCR_UPTO = :NEW.MIGDEP_INT_ACCR_UPTO
       WHERE ACNTS_ACNUM = :OLD.MIGDEP_DEP_AC_NUM;

      UPDATE MIG_DEPIA D
         SET D.DEPIA_DATE_OF_ENTRY = :NEW.MIGDEP_INT_ACCR_UPTO,
             D.DEPIA_ACCR_UPTO_DATE = :NEW.MIGDEP_INT_ACCR_UPTO
       WHERE     D.DEPIA_ACCOUNTNUM = :OLD.MIGDEP_DEP_AC_NUM
             AND D.DEPIA_ENTRY_TYPE = 'IP'
             AND D.DEPIA_DATE_OF_ENTRY =
                    (SELECT MAX (DEPIA_DATE_OF_ENTRY)
                       FROM MIG_DEPIA
                      WHERE     DEPIA_ACCOUNTNUM = :OLD.MIGDEP_DEP_AC_NUM
                            AND DEPIA_ENTRY_TYPE = 'IP');
   END IF;


   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_ACCRUAL ENABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_ACNTS_PAID ENABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_ACCRU ENABLE';
   EXECUTE IMMEDIATE V_SQL;

   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNAC_APPLIED ENABLE';
   EXECUTE IMMEDIATE V_SQL;
   
   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_PBDCONT_PAID ENABLE';
   EXECUTE IMMEDIATE V_SQL;
END UPDATE_CHECK_MIG_PBDCONT_ACCRU;
/
