CREATE OR REPLACE TRIGGER UPDATE_CHECK_MIG_ASSETCLS
   BEFORE UPDATE OF ASSETCLSH_ASSET_CODE
   ON MIG_ASSETCLS
   FOR EACH ROW
DECLARE
   V_SQL   VARCHAR2 (100);
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
   V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNACNTS_ASSET DISABLE';

   EXECUTE IMMEDIATE V_SQL;


   UPDATE MIG_LNACNT
      SET LNACNT_ASSET_STAT = :NEW.ASSETCLSH_ASSET_CODE
    WHERE LNACNT_ACNUM = :OLD.ASSETCLS_ACNUM;
    V_SQL := 'ALTER TRIGGER UPDATE_CHECK_MIG_LNACNTS_ASSET ENABLE';

   EXECUTE IMMEDIATE V_SQL;
END UPDATE_CHECK_MIG_ASSETCLS;
/
SHOW ERRORS;
/