/* Formatted on 8/19/2019 5:25:00 PM (QP5 v5.227.12220.39754) */
SELECT FACNO (ACNTS_ENTITY_NUM, ACNTS_INTERNAL_ACNUM) ACCOUNTNUMBER,
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNTTITLE,
       (SELECT PRODUCT_NAME
          FROM PRODUCTS
         WHERE PRODUCT_CODE = ACNTS_PROD_CODE)
          PRODUCTNAME,
       ACNTS_CLIENT_NUM CUSTOMERNO,
       NULL PRODUCTCATEGORY,
       NULL OWNERSHIPTYPE,
       ACNTS.ACNTS_CURR_CODE CURRENCY,
       ACNTS.ACNTS_OPENING_DATE OPENINGDATE,
       ACNTS.ACNTS_BRN_CODE CBSBRANCHCODE,
       ACNTS.ACNTS_ENTD_ON ACCOUNTCREATIONDATE,
       TRANPROFILE.ACTPH_SRC_FUND TYPEOFBUSINESSORSOURCEOFINCOME,
       TRANPROFILE.ACTPH_NOT_CASHR DTRNOCASH,                             ----
       TRANPROFILE.ACTPH_CUTOFF_LMT_CASHR DMAXTRAMOUNTCASH,
       TRANPROFILE.ACTPH_MAXAMT_CASHR DMONTHLYTOTALAMOUNTCASH,
       TRANPROFILE.ACTPH_NOT_NONCASHR DTRNOTRANSFER,
       TRANPROFILE.ACTPH_CUTOFF_LMT_NONCASHR DMAXTRAMOUNTTRANSFER,
       TRANPROFILE.ACTPH_MAXAMT_NCASHR DMONTHLYTOTALAMOUNTTRANSFER,
       TRANPROFILE.ACTPH_NOT_TFREMR DTRNOREMITANCE,
       TRANPROFILE.ACTPH_CUTOFF_LMT_TFREMR DMAXTRAMOUNTREMITTANCE,
       TRANPROFILE.ACTPH_MAXAMT_TFREMR DMONTHLYTOTALAMOUNTREMITTANCE,
       NULL DTRNOEXPORT,
       NULL DMAXTRAMOUNTEXPORT,
       NULL DMONTHLYTOTALAMOUNTEXPORT,
       TRANPROFILE.ACTPH_NOT_NONTFREMR DTRNOOTHERS,
       TRANPROFILE.ACTPH_CUTOFF_LMT_NONTFREMR DMAXTRAMOUNTOTHERS,
       TRANPROFILE.ACTPH_MAXAMT_NONTFREMR DMONTHLYTOTALAMOUNTOTHERS,
         ACTPH_MAXAMT_CASHR
       + ACTPH_MAXAMT_NCASHR
       + ACTPH_MAXAMT_TFREMR
       + ACTPH_MAXAMT_NONTFREMR
          TOTALMONTHLYDEPOSOIT,                                            ---
       TRANPROFILE.ACTPH_NOT_CASHP WTRNOCASH,
       TRANPROFILE.ACTPH_CUTOFF_LMT_CASHP WMAXTRAMOUNTCASH,
       TRANPROFILE.ACTPH_MAXAMT_CASHP WMONTHLYTOTALAMOUNTCASH,
       TRANPROFILE.ACTPH_NOT_NONCASHP WTRNOTRANSFER,
       TRANPROFILE.ACTPH_CUTOFF_LMT_NONCASHP WMAXTRAMOUNTTRANSFER,
       TRANPROFILE.ACTPH_MAXAMT_NCASHP WMONTHLYTOTALAMOUNTTRANSFER,
       TRANPROFILE.ACTPH_NOT_TFREMP WTRNOREMITANCE,
       TRANPROFILE.ACTPH_CUTOFF_LMT_TFREMP WMAXTRAMOUNTREMITANCE,
       TRANPROFILE.ACTPH_MAXAMT_TFREMP WMONTHLYTOTALAMOUNTREMITANCE,
       NULL WTRNOIMPORT,
       NULL WMAXTRAMOUNTIMPORT,
       NULL WMONTHLYTOTALAMOUNTIMPORT,
       TRANPROFILE.ACTPH_NOT_NONTFREMP WTRNOOTHERS,
       TRANPROFILE.ACTPH_CUTOFF_LMT_NONTFREMP WMAXTRAMOUNTOTHERS,
       TRANPROFILE.ACTPH_MAXAMT_NONTFREMP WMONTHLYTOTALAMOUNTOTHERS,
         ACTPH_MAXAMT_CASHP
       + ACTPH_MAXAMT_NCASHP
       + ACTPH_MAXAMT_TFREMP
       + ACTPH_MAXAMT_NONTFREMP
          TOTALMONTHLYWITHDRAWAL,
       ACNTS_LAST_MOD_ON ACCOUNTUPDATEDATE,
       CASE
          WHEN ACNTS_INOP_ACNT = 1 OR ACNTS_DORMANT_ACNT = 1 THEN 1
          ELSE 0
       END
          ISDORMANT,
       NULL ISSIGNATORY,
       NULL TRAKINGNO,
       CASE WHEN ACNTS_CLOSURE_DATE IS NULL THEN 1 ELSE 0 END ISACTIVE,
       ACNTS_CLOSURE_DATE ACCCLOSINGDATE
  FROM ACNTS
       LEFT OUTER JOIN
       (SELECT ACNTRNPRHIST.*
          FROM ACNTRNPRHIST,
               (  SELECT ACTPH_ACNT_NUM,
                         MAX (ACTPH_LATEST_EFF_DATE) ACTPH_LATEST_EFF_DATE
                    FROM ACNTRNPRHIST
                GROUP BY ACTPH_ACNT_NUM) MAXACNTRNPR
         WHERE     ACNTRNPRHIST.ACTPH_ACNT_NUM = MAXACNTRNPR.ACTPH_ACNT_NUM
               AND ACNTRNPRHIST.ACTPH_LATEST_EFF_DATE =
                      MAXACNTRNPR.ACTPH_LATEST_EFF_DATE) TRANPROFILE
          ON (ACNTS.ACNTS_INTERNAL_ACNUM = TRANPROFILE.ACTPH_ACNT_NUM)
 WHERE ACNTS_ENTITY_NUM = 1 AND ACNTS_BRN_CODE = 380 ;