CREATE OR REPLACE PROCEDURE SP_TRAN_DATA_GEN_AML_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(1,50); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(51,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(101,150); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(151,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(201,250); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(251,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(301,350); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(351,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(401,450); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(451,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(501,550); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(551,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TRAN_DATA_GEN_AML(601,700); end;',instance=>1); 
  COMMIT;
END SP_TRAN_DATA_GEN_AML_THREAD;
/
