8259798


SELECT FACNO (TRAN_ENTITY_NUM, TRAN_INTERNAL_ACNUM) ACCOUNTORREFERENCENO,
       TRAN_BRN_CODE || '/' || TRAN_DATE_OF_TRAN || '/' || TRAN_BATCH_NUMBER
          TRANSACTIONNO,
       CASE WHEN TRAN_DB_CR_FLG = 'D' THEN 'DR' ELSE 'CR' END TRANSACTIONTYPE,
       CASE
          WHEN TRAN_TYPE_OF_TRAN = 1 THEN 'TRANSFER'
          WHEN TRAN_TYPE_OF_TRAN = 2 THEN 'CLEARING'
          WHEN TRAN_TYPE_OF_TRAN = 3 THEN 'CASH'
       END
          TRANSACTIONMEDIA,
       TRAN_AMOUNT AMOUNT,
       TRAN_AVAILABLE_AC_BAL BALANCE,
       TRAN_CURR_CODE CURRENCY,
       NULL BENEFICIARYNAME,
       TRAN_ENTD_BY TELLERID,
       TRAN_DATE_OF_TRAN TRANSACTIONDATE,
       TRAN_ENTD_ON TRANSACTIONTIMESTAMP,
       --TO_CHAR(TRAN_ENTD_ON, 'HH24:MI:SS') TRANSACTIONTIMESTAMP,
       TRAN_BRN_CODE CBSBRANCHCODE,
       NULL GEOLOCATION,
       CASE
          WHEN TRIM (TRAN_NARR_DTL1 || TRAN_NARR_DTL2 || TRAN_NARR_DTL3)
                  IS NOT NULL
          THEN
             TRIM (TRAN_NARR_DTL1 || TRAN_NARR_DTL2 || TRAN_NARR_DTL3)
          ELSE
             TRIM (
                TRANBAT_NARR_DTL1 || TRANBAT_NARR_DTL2 || TRANBAT_NARR_DTL3)
       END
          COMMENTS,
       FACNO (TRAN_ENTITY_NUM, TRAN_INTERNAL_ACNUM) BENIFICIARYACNO,
       MBRN_NAME BENIFICIARYBRANCHNAME,
       (SELECT INS_NAME_OF_BANK FROM INSTALL) BENIFICIARYBANKNAME,
       (SELECT CT_PERSON_NAME
          FROM CTRAN2019
         WHERE     POST_TRAN_BRN = TRAN_BRN_CODE
               AND POST_TRAN_DATE = TRANBAT_DATE_OF_TRAN
               AND POST_TRAN_BATCH_NUM = TRANBAT_BATCH_NUMBER
               AND POST_TRAN_BRN = 380)
          DEPOSITORNAME,
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME
  FROM TRAN2019,
       TRANBAT2019,
       ACNTS,
       MBRN
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRANBAT_ENTITY_NUM = TRAN_ENTITY_NUM
       AND TRANBAT_BRN_CODE = TRAN_BRN_CODE
       AND TRANBAT_DATE_OF_TRAN = TRAN_DATE_OF_TRAN
       AND TRANBAT_BATCH_NUMBER = TRAN_BATCH_NUMBER
       AND TRAN_INTERNAL_ACNUM <> 0
       AND TRAN_AUTH_BY IS NOT NULL
       AND ACNTS_ENTITY_NUM = TRAN_ENTITY_NUM
       AND ACNTS_INTERNAL_ACNUM = TRAN_INTERNAL_ACNUM
       AND MBRN_ENTITY_NUM = 1
       AND MBRN_CODE = TRAN_BRN_CODE
       AND TRAN_BRN_CODE = 380;