Insert into EODSODPGMLIST
   (ESPGMLIST_PROCESS_NAME, ESPGMLIST_PROCESS_DESCN, ESPGMLIST_PROC_ACNT_LIMIT)
 Values
   ('PKG_TREASURY_BAL_TRF.SP_BAL_TRANSFER', 'Treasury Balance Transfer from Settlement GL to BB Principle', 0);
   
Insert into EODSODPGMLIST
   (ESPGMLIST_PROCESS_NAME, ESPGMLIST_PROCESS_DESCN, ESPGMLIST_PROC_ACNT_LIMIT)
 Values
   ('PKG_GAIN_GL_TRF.START_BRNWISE', 'Balance Transfer to separate Gain and Loss GL', 0);
   
Insert into EODSODPGMLIST
   (ESPGMLIST_PROCESS_NAME, ESPGMLIST_PROCESS_DESCN, ESPGMLIST_PROC_ACNT_LIMIT)
 Values
   ('PKG_DEAL_ED_DEDUCTION.SP_ED_DEDUCTION', 'Treasury deal ED Deduction', 0);
   
COMMIT;