Insert into EODSODPROCDTL
   (ESPROCDTL_ENTITY_NUM, ESPROCDTL_RUN_STAGE, ESPROCDTL_SEQ_SL, ESPROCDTL_PROCESS_NAME, ESPROCDTL_RUN_FREQ, 
    ESPROCDTL_DISABLED)
 Values
   (1, 'E', 28.1, 'PKG_TREASURY_BAL_TRF.SP_BAL_TRANSFER', 'D', 
    '1');
	
Insert into EODSODPROCDTL
   (ESPROCDTL_ENTITY_NUM, ESPROCDTL_RUN_STAGE, ESPROCDTL_SEQ_SL, ESPROCDTL_PROCESS_NAME, ESPROCDTL_RUN_FREQ, 
    ESPROCDTL_DISABLED)
 Values
   (1, 'E', 28.2, 'PKG_GAIN_GL_TRF.START_BRNWISE', 'D', 
    '1');
	
Insert into EODSODPROCDTL
   (ESPROCDTL_ENTITY_NUM, ESPROCDTL_RUN_STAGE, ESPROCDTL_SEQ_SL, ESPROCDTL_PROCESS_NAME, ESPROCDTL_RUN_FREQ, 
    ESPROCDTL_DISABLED)
 Values
   (1, 'E', 28.3, 'PKG_DEAL_ED_DEDUCTION.SP_ED_DEDUCTION', 'Y', 
    '1');
	
COMMIT;
