CREATE TABLE OCCUPATIONS_MAPPING
(
   OCCUPATIONS_CODE    VARCHAR2 (6 BYTE),
   OCCUPATIONS_DESCN   VARCHAR2 (50 BYTE),
   Profession_Name     VARCHAR2 (500 BYTE),
   Profession_cODE     VARCHAR2 (6 BYTE)
);

INSERT INTO OCCUPATIONS_MAPPING
SELECT OCCUPATIONS_CODE, OCCUPATIONS_DESCN, OCCUPATIONS_DESCN, ROWNUM + 1000 fROM OCCUPATIONS ;