CREATE OR REPLACE PROCEDURE SP_GEN_AML_CLIENT_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(1,50); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(51,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(101,150); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(151,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(201,250); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(251,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(301,350); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(351,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(401,450); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(451,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(501,550); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(551,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_CLIENT_DATA(601,700); end;',instance=>1); 
  COMMIT;
END SP_GEN_AML_CLIENT_THREAD;
/
