CREATE OR REPLACE PROCEDURE SP_GEN_TP_DATA_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1,50); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(51,100); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(101,150); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(151,200); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(201,250); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(251,300); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(301,350); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(351,400); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(401,450); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(451,500); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(501,550); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(551,600); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(601,650); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(651,700); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(701,750); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(751,800); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(801,850); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(851,900); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(901,950); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(951,1000); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1001,1050); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1051,1100); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1101,1150); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1151,1200); end;');
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1201,1250); end;'); 
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1251,1300); end;'); 
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_TP_DATA(1301,1350); end;'); 
  COMMIT;
END SP_GEN_TP_DATA_THREAD;
/
