ALTER TABLE ACBALASONHIST_MAX_TRAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE ACBALASONHIST_MAX_TRAN CASCADE CONSTRAINTS;

CREATE TABLE ACBALASONHIST_MAX_TRAN
(
  ACBALH_ENTITY_NUM      NUMBER(4)              NOT NULL,
  ACBALH_INTERNAL_ACNUM  NUMBER(14)             NOT NULL,
  ACBALH_ASON_DATE       DATE                   NOT NULL,
  ACBALH_AC_BAL          NUMBER(18,3)           DEFAULT 0,
  ACBALH_BC_BAL          NUMBER(18,3)           DEFAULT 0,
  ACBALH_BRN_CODE        NUMBER(6),
  ACBALH_ASON_AC_BAL     NUMBER(18,3),
  ACBALH_ASON_BC_BAL     NUMBER(18,3)
)
PARTITION BY RANGE(ACBALH_BRN_CODE)
  INTERVAL(1) STORE IN (DATA)
  (PARTITION EMPTY VALUES LESS THAN (1000) TABLESPACE DATA) ; 


CREATE UNIQUE INDEX PK_ACBLASONHST_MX_TRN ON ACBALASONHIST_MAX_TRAN
(ACBALH_ENTITY_NUM, ACBALH_INTERNAL_ACNUM, ACBALH_ASON_DATE)
LOGGING
TABLESPACE CBSINDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ACBALASONHIST_MAX_TRAN ADD (
  CONSTRAINT PK_ACBLASONHST_MX_TRN
  PRIMARY KEY
  (ACBALH_ENTITY_NUM, ACBALH_INTERNAL_ACNUM, ACBALH_ASON_DATE)
  USING INDEX PK_ACBLASONHST_MX_TRN
  ENABLE VALIDATE);


