CREATE TABLE BRNACLIST
(
  BR_CODE                NUMBER(6),
  CLIENT_ID              NUMBER(12),
  ACCOUNT_NO             VARCHAR2(35 BYTE),
  ACC_TITLE              VARCHAR2(100 BYTE),
  PRODUCT_CODE           NUMBER(4),
  PRODUCT_NAME           VARCHAR2(50 BYTE),
  ACTYPE_CODE            VARCHAR2(5 BYTE),
  ACTYPE_DESCN           VARCHAR2(50 BYTE),
  ACSUB_SUBTYPE_CODE     NUMBER(3),
  ACSUB_DESCN            VARCHAR2(50 BYTE),
  INDCLIENT_FATHER_NAME  VARCHAR2(153 BYTE),
  INDCLIENT_MOTHER_NAME  VARCHAR2(153 BYTE),
  SPOUSE_NAME            VARCHAR2(100 BYTE),
  PERMANENT_ADDRESS      VARCHAR2(4000 BYTE),
  PRESENT_ADDRESS        VARCHAR2(4000 BYTE),
  BUSINESS_ADDRESS       VARCHAR2(4000 BYTE),
  BIRTH_PLACE            VARCHAR2(50 BYTE),
  INDCLIENT_SEX          VARCHAR2(153 BYTE),
  INDCLIENT_BIRTH_DATE   VARCHAR2(153 BYTE),
  NID                    VARCHAR2(35 BYTE),
  INDCLIENT_TEL_RES      VARCHAR2(153 BYTE),
  INDCLIENT_TEL_GSM      VARCHAR2(153 BYTE),
  TIN                    VARCHAR2(35 BYTE),
  ETIN                   CHAR(35 BYTE),
  PASSPORT               VARCHAR2(35 BYTE),
  DRIVING_LICENCE        VARCHAR2(35 BYTE),
  OUTSTANDING            NUMBER(18,2)
)
TABLESPACE TBFES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
