CREATE TABLE ERRORLOG
(
  TEMPLATE_NAME  VARCHAR2(100 BYTE),
  COLUMN_NAME    VARCHAR2(100 BYTE),
  ROW_COUNT      NUMBER,
  SUGGESTION     VARCHAR2(1000 BYTE),
  QUERY          VARCHAR2(3000 BYTE)
);