CREATE OR REPLACE PROCEDURE SP_DEPIA_VALIDATE (
   P_BRANCH_CODE       IN NUMBER,
   P_START_DATE        IN DATE)
IS
   W_SQL               VARCHAR2 (3000);
   W_BRN_CODE          NUMBER (5) := P_BRANCH_CODE;
   W_MIG_DATE          DATE := P_START_DATE;
   W_ROWCOUNT          NUMBER := 0;
   
   
   
BEGIN
   DELETE FROM ERRORLOG
         WHERE TEMPLATE_NAME = 'MIG_DEPIA';
   COMMIT;
   
   
--- branch code checking


SELECT COUNT(*)
  INTO W_ROWCOUNT
  FROM MIG_DEPIA
 WHERE DEPIA_BRN_CODE <> W_BRN_CODE;

IF W_ROWCOUNT > 0 
  THEN
    
  INSERT INTO ERRORLOG
    (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
  VALUES
    ('MIG_DEPIA',
     'DEPIA_BRN_CODE',
     W_ROWCOUNT,
     'MIGDEP_BRN_CODE SHOULD BE ' || W_BRN_CODE,
     'SELECT DEPIA_ACCOUNTNUM, DEPIA_BRN_CODE FROM MIG_DEPIA  WHERE DEPIA_BRN_CODE <> ' ||
     W_BRN_CODE);
     
    END IF;       
          
--- checking contact no
         
  SELECT COUNT(*)
    INTO W_ROWCOUNT
    FROM MIG_DEPIA
   WHERE DEPIA_CONTRACT_NUM NOT IN (0, 1);
  IF W_ROWCOUNT > 0 THEN
  
    INSERT INTO ERRORLOG
      (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
    VALUES
      ('MIG_DEPIA',
       'MIGDEP_CONT_NUM',
       W_ROWCOUNT,
       'DEPIA_CONTRACT_NUM VALUE CANNOT BE OTHER THAN 0 OR 1' ,
       'SELECT DEPIA_ACCOUNTNUM , DEPIA_CONTRACT_NUM FROM MIG_DEPIA
       WHERE DEPIA_CONTRACT_NUM NOT IN (0, 1);');
  
  END IF;


--- matching account no with acnts


    SELECT COUNT(*) INTO W_ROWCOUNT
        FROM MIG_DEPIA
       WHERE DEPIA_ACCOUNTNUM NOT IN
                (SELECT MIG_ACNTS.ACNTS_ACNUM FROM MIG_ACNTS);

IF W_ROWCOUNT > 0 THEN
   INSERT INTO ERRORLOG (TEMPLATE_NAME,
                         COLUMN_NAME,
                         ROW_COUNT,
                         SUGGESTION,
                         QUERY)
        VALUES ('MIG_DEPIA',
                'DEPIA_ACCOUNTNUM',
                W_ROWCOUNT,
                'ACCOUNT NUMBER IS NOT IN MIG_ACNTS',
                'SELECT DEPIA_ACCOUNTNUM
        FROM MIG_DEPIA
       WHERE DEPIA_ACCOUNTNUM NOT IN
                (SELECT MIG_ACNTS.ACNTS_ACNUM FROM MIG_ACNTS);');
    END IF ;
    
---Date of entry is greater than migration date
    
SELECT COUNT(*)
  INTO W_ROWCOUNT
  FROM MIG_DEPIA
 WHERE DEPIA_DATE_OF_ENTRY > P_START_DATE;

IF W_ROWCOUNT > 0 THEN

  INSERT INTO ERRORLOG
    (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
  VALUES
    ('MIG_DEPIA',
     'DEPIA_DATE_OF_ENTRY',
     W_ROWCOUNT,
     'DEPIA_DATE_OF_ENTRY CAN NOT BE GREATER THAN MIGRATION DATE',
     'SELECT DEPIA_ACCOUNTNUM, DEPIA_DATE_OF_ENTRY 
  FROM MIG_DEPIA
 WHERE DEPIA_DATE_OF_ENTRY > ''' || P_START_DATE || '''');

END IF;

 
END SP_DEPIA_VALIDATE;
/