CREATE OR REPLACE PROCEDURE SP_LN_INT_APPLIED_UPTO(P_MIG_DATE DATE) IS
  V_MIG_DATE           DATE := P_MIG_DATE;
  V_COUNT              NUMBER;
  V_YEAR_END_DATE      DATE;
  V_HALF_YEAR_END_DATE DATE;
  V_QUARTER_END_DATE   DATE;
BEGIN

  SELECT TRUNC(V_MIG_DATE, 'YEAR') - 1 INTO V_YEAR_END_DATE FROM DUAL;


  SELECT CASE
           WHEN ADD_MONTHS(TRUNC(V_MIG_DATE, 'YEAR'), 6) - 1 > V_MIG_DATE THEN
            TRUNC(V_MIG_DATE, 'YEAR') - 1
           ELSE
            ADD_MONTHS(TRUNC(V_MIG_DATE, 'YEAR'), 6) - 1
         END
    INTO V_HALF_YEAR_END_DATE
    FROM DUAL;


  SELECT FN_FIND_QUARTER_END_DATE(V_MIG_DATE)
    INTO V_QUARTER_END_DATE
    FROM DUAL;

  SELECT COUNT(*)
    INTO V_COUNT
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <> V_QUARTER_END_DATE -------- Quarter end date
     AND L.LNACNT_ASSET_STAT IN ('UC', 'SM')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = 'Q');
 
  
  
 IF V_COUNT > 0 THEN
  
    INSERT INTO ERRORLOG
      (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
    VALUES
      ('MIG_LNACNT',
       'LNACNT_INT_APPLIED_UPTO_DATE',
       V_COUNT,
       'LNACNT_INT_APPLIED_UPTO_DATE SHOULD BE QUARTER END DATE FOR QUARTERLY PRODUCTS',
       'SELECT ACNTS_ACNUM , ACNTS_PROD_CODE ,  LNACNT_INT_APPLIED_UPTO_DATE
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <>  ''' || V_QUARTER_END_DATE || '''
     AND L.LNACNT_ASSET_STAT IN (''UC'', ''SM'')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = ''Q'');');
  
  END IF;

  SELECT COUNT(*)
    INTO V_COUNT
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <> V_HALF_YEAR_END_DATE -------- Quarter end date
     AND L.LNACNT_ASSET_STAT IN ('UC', 'SM')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = 'H');

  IF V_COUNT > 0 THEN
  
    INSERT INTO ERRORLOG
      (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
    VALUES
      ('MIG_LNACNT',
       'LNACNT_INT_APPLIED_UPTO_DATE',
       V_COUNT,
       'LNACNT_INT_APPLIED_UPTO_DATE SHOULD BE HALF YEAR END DATE FOR HALF YEARLY PRODUCTS',
       'SELECT ACNTS_ACNUM , ACNTS_PROD_CODE ,  LNACNT_INT_APPLIED_UPTO_DATE
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <>  ''' || V_HALF_YEAR_END_DATE || '''
     AND L.LNACNT_ASSET_STAT IN (''UC'', ''SM'')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = ''H'');');
  
  END IF;

  SELECT COUNT(*)
    INTO V_COUNT
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <> V_YEAR_END_DATE -------- Quarter end date
     AND L.LNACNT_ASSET_STAT IN ('UC', 'SM')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = 'Y');

  IF V_COUNT > 0 THEN
  
    INSERT INTO ERRORLOG
      (TEMPLATE_NAME, COLUMN_NAME, ROW_COUNT, SUGGESTION, QUERY)
    VALUES
      ('MIG_LNACNT',
       'LNACNT_INT_APPLIED_UPTO_DATE',
       V_COUNT,
       'LNACNT_INT_APPLIED_UPTO_DATE SHOULD BE YEAR END DATE FOR YEARLY PRODUCTS',
       'SELECT ACNTS_ACNUM , ACNTS_PROD_CODE ,  LNACNT_INT_APPLIED_UPTO_DATE
    FROM MIG_LNACNT L, MIG_ACNTS A
   WHERE A.ACNTS_ACNUM = L.LNACNT_ACNUM
     AND L.LNACNT_INT_APPLIED_UPTO_DATE <>  ''' || V_YEAR_END_DATE || '''
     AND L.LNACNT_ASSET_STAT IN (''UC'', ''SM'')
     AND A.ACNTS_PROD_CODE IN
         (SELECT LNPRODPM.LNPRD_PROD_CODE
            FROM LNPRODPM
           WHERE LNPRODPM.LNPRD_INT_APPL_FREQ = ''Y'');');
  
  END IF;

END SP_LN_INT_APPLIED_UPTO;
/